### ISSUE TITLE
 namespaceURI .../csi/omniclass-1 doesn't exist within bSDD

### ISSUE THREAD

**Issue by araccaine** [buildingSMART/bSDD#34]
**Describe the bug**
The `namespaceURI` for Omniclass 1 isn't working respectively doesn't exist in bSDD

**To Reproduce**
E.g. use a terminal to execute:
```sh
curl -X 'GET' \
  'https://api.bsdd.buildingsmart.org/api/Classification/v3?namespaceUri=http%3A%2F%2Fidentifier.buildingsmart.org%2Furi%2Fcsi%2Fomniclass-1&includeChildClassificationReferences=true' \
  -H 'accept: text/plain'
```

Or use [swaggerhub with Domain/get_api_Domain_v3_Classifications](https://app.swaggerhub.com/apis/buildingSMART/Dictionaries/v1#/Domain/get_api_Domain_v3_Classifications) and use `http://identifier.buildingsmart.org/uri/csi/omniclass-1` as `namespaceUri`

**Expected behavior**
Response should hold classifications for Omniclass.

**Actual behavior**
Code 400: "Domain with namespace 'http://identifier.buildingsmart.org/uri/csi/omniclass-1" not found"

(see similar problem in #26 )

EDIT
for API Version /Classification/v2 the namespaceUri exists for Omniclass.

**Comment by Baars-IT** [comment]
Hi Eric,

The Classification API will return details of one classification, you cannot pass a domain namespace uri to that API.

By the looks of it, you should use the API [/api/Domain/v2/Classifications](https://app.swaggerhub.com/apis/buildingSMART/Dictionaries/v1#/Domain/get_api_Domain_v2_Classifications)

Btw, the "Omniclass" domain in bSDD is empty (probably due to licensing restrictions, not sure about that)

**Comment by araccaine** [comment]
Thank you very much for your reply! I think I mixed up the API paths (this would also explain my confusion with `v2` and `v3` ...).

The Omniclass is empty indeed; due to licensing restrictions sounds reasonable.
