### ISSUE TITLE
How to define USERDEFINED types in RelatedIfcEntityNamesList

### ISSUE THREAD

**Issue by araccaine** [buildingSMART/bSDD#97]
As I understand the [documentation](https://github.com/buildingSMART/bSDD/blob/master/Documentation/bSDD%20JSON%20import%20model.md#class), the field `RelatedIfcEntityNamesList` can have multiple related IFC entitites.

- Without any type would be e.g. `"RelatedIfcEntityNamesList": [ "IfcBeam" ]`
- A `IfcBeam` with predefined type `LINTEL` would be e.g. `"RelatedIfcEntityNamesList": [ "IfcBeamLINTEL" ]`

But how do we define a `IfcBeam` with the USERDEFINED type `MyBeam`? Do we need to define a new relation with `IsChildOf` or something like that?

**Comment by atomczak** [comment]
You're correct with the `"RelatedIfcEntityNamesList": [ "IfcBeamLINTEL" ]` example. You can't use USERDEFINED because that is not a defined class in IFC dictionary. I know there is a dichotomy between official IFC4.3 and what we published in bSDD. 

That is because we are trying to educate people not to use USERDEFINED and NOTDEFINED options, and instead simply leave the predefined type empty and assign a class (IfcClassificationReference) to a registered term. This way we increase consistency of the information.

To answer to your use case, I recommend modeling this as an IfcBeam without predefined type, with an IfcClassificationReference to `MyBeam` from your dictionary. And yes, `MyBeam` can be registered with relation `IsChildOf` IfcBeam. The added value of this approach is that one element can have multiple class references (for example if you are using multiple systems), which was not possible with predefined types.
